name: app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  uuid: ^3.0.7
  intl: ^0.20.2
  parse_server_sdk_flutter: ^9.0.0
  sembast_web: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
